export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'
export const USER_PROFILE_UPDATE_RESET = 'USER_PROFILE_UPDATE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const USER_EDUCATION_CREATE_REQUEST = 'USER_EDUCATION_CREATE_REQUEST'
export const USER_EDUCATION_CREATE_SUCCESS = 'USER_EDUCATION_CREATE_SUCCESS'
export const USER_EDUCATION_CREATE_FAIL = 'USER_EDUCATION_CREATE_FAIL'

export const USER_EDUCATION_UPDATE_REQUEST = 'USER_EDUCATION_UPDATE_REQUEST'
export const USER_EDUCATION_UPDATE_SUCCESS = 'USER_EDUCATION_UPDATE_SUCCESS'
export const USER_EDUCATION_UPDATE_FAIL = 'USER_EDUCATION_UPDATE_FAIL'

export const USER_EDUCATION_DELETE_REQUEST = 'USER_EDUCATION_DELETE_REQUEST'
export const USER_EDUCATION_DELETE_SUCCESS = 'USER_EDUCATION_DELETE_SUCCESS'
export const USER_EDUCATION_DELETE_FAIL = 'USER_EDUCATION_DELETE_FAIL'

export const USER_EDUCATION_GET_REQUEST = 'USER_EDUCATION_GET_REQUEST'
export const USER_EDUCATION_GET_SUCCESS = 'USER_EDUCATION_GET_SUCCESS'
export const USER_EDUCATION_GET_FAIL = 'USER_EDUCATION_GET_FAIL'
export const USER_EDUCATION_GET_RESET = 'USER_EDUCATION_GET_RESET'

export const USER_WORK_EXPERIENCE_CREATE_REQUEST =
  'USER_WORK_EXPERIENCE_CREATE_REQUEST'
export const USER_WORK_EXPERIENCE_CREATE_SUCCESS =
  'USER_WORK_EXPERIENCE_CREATE_SUCCESS'
export const USER_WORK_EXPERIENCE_CREATE_FAIL =
  'USER_WORK_EXPERIENCE_CREATE_FAIL'

export const USER_WORK_EXPERIENCE_UPDATE_REQUEST =
  'USER_WORK_EXPERIENCE_UPDATE_REQUEST'
export const USER_WORK_EXPERIENCE_UPDATE_SUCCESS =
  'USER_WORK_EXPERIENCE_UPDATE_SUCCESS'
export const USER_WORK_EXPERIENCE_UPDATE_FAIL =
  'USER_WORK_EXPERIENCE_UPDATE_FAIL'

export const USER_WORK_EXPERIENCE_DELETE_REQUEST =
  'USER_WORK_EXPERIENCE_DELETE_REQUEST'
export const USER_WORK_EXPERIENCE_DELETE_SUCCESS =
  'USER_WORK_EXPERIENCE_DELETE_SUCCESS'
export const USER_WORK_EXPERIENCE_DELETE_FAIL =
  'USER_WORK_EXPERIENCE_DELETE_FAIL'

export const USER_WORK_EXPERIENCE_GET_REQUEST =
  'USER_WORK_EXPERIENCE_GET_REQUEST'
export const USER_WORK_EXPERIENCE_GET_SUCCESS =
  'USER_WORK_EXPERIENCE_GET_SUCCESS'
export const USER_WORK_EXPERIENCE_GET_FAIL = 'USER_WORK_EXPERIENCE_GET_FAIL'

export const USER_REFERENCE_CREATE_REQUEST = 'USER_REFERENCE_CREATE_REQUEST'
export const USER_REFERENCE_CREATE_SUCCESS = 'USER_REFERENCE_CREATE_SUCCESS'
export const USER_REFERENCE_CREATE_FAIL = 'USER_REFERENCE_CREATE_FAIL'

export const USER_REFERENCE_UPDATE_REQUEST = 'USER_REFERENCE_UPDATE_REQUEST'
export const USER_REFERENCE_UPDATE_SUCCESS = 'USER_REFERENCE_UPDATE_SUCCESS'
export const USER_REFERENCE_UPDATE_FAIL = 'USER_REFERENCE_UPDATE_FAIL'

export const USER_REFERENCE_DELETE_REQUEST = 'USER_REFERENCE_DELETE_REQUEST'
export const USER_REFERENCE_DELETE_SUCCESS = 'USER_REFERENCE_DELETE_SUCCESS'
export const USER_REFERENCE_DELETE_FAIL = 'USER_REFERENCE_DELETE_FAIL'

export const USER_REFERENCE_GET_REQUEST = 'USER_REFERENCE_GET_REQUEST'
export const USER_REFERENCE_GET_SUCCESS = 'USER_REFERENCE_GET_SUCCESS'
export const USER_REFERENCE_GET_FAIL = 'USER_REFERENCE_GET_FAIL'

export const USER_SKILL_CREATE_REQUEST = 'USER_SKILL_CREATE_REQUEST'
export const USER_SKILL_CREATE_SUCCESS = 'USER_SKILL_CREATE_SUCCESS'
export const USER_SKILL_CREATE_FAIL = 'USER_SKILL_CREATE_FAIL'

export const USER_SKILL_UPDATE_REQUEST = 'USER_SKILL_UPDATE_REQUEST'
export const USER_SKILL_UPDATE_SUCCESS = 'USER_SKILL_UPDATE_SUCCESS'
export const USER_SKILL_UPDATE_FAIL = 'USER_SKILL_UPDATE_FAIL'

export const USER_SKILL_DELETE_REQUEST = 'USER_SKILL_DELETE_REQUEST'
export const USER_SKILL_DELETE_SUCCESS = 'USER_SKILL_DELETE_SUCCESS'
export const USER_SKILL_DELETE_FAIL = 'USER_SKILL_DELETE_FAIL'

export const USER_SKILL_GET_REQUEST = 'USER_SKILL_GET_REQUEST'
export const USER_SKILL_GET_SUCCESS = 'USER_SKILL_GET_SUCCESS'
export const USER_SKILL_GET_FAIL = 'USER_SKILL_GET_FAIL'

export const USER_PROJECT_CREATE_REQUEST = 'USER_PROJECT_CREATE_REQUEST'
export const USER_PROJECT_CREATE_SUCCESS = 'USER_PROJECT_CREATE_SUCCESS'
export const USER_PROJECT_CREATE_FAIL = 'USER_PROJECT_CREATE_FAIL'

export const USER_PROJECT_UPDATE_REQUEST = 'USER_PROJECT_UPDATE_REQUEST'
export const USER_PROJECT_UPDATE_SUCCESS = 'USER_PROJECT_UPDATE_SUCCESS'
export const USER_PROJECT_UPDATE_FAIL = 'USER_PROJECT_UPDATE_FAIL'

export const USER_PROJECT_DELETE_REQUEST = 'USER_PROJECT_DELETE_REQUEST'
export const USER_PROJECT_DELETE_SUCCESS = 'USER_PROJECT_DELETE_SUCCESS'
export const USER_PROJECT_DELETE_FAIL = 'USER_PROJECT_DELETE_FAIL'

export const USER_PROJECT_GET_REQUEST = 'USER_PROJECT_GET_REQUEST'
export const USER_PROJECT_GET_SUCCESS = 'USER_PROJECT_GET_SUCCESS'
export const USER_PROJECT_GET_FAIL = 'USER_PROJECT_GET_FAIL'
